# -*- coding: utf-8 -*-
"""Mundial 2026 - versión 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4QD9-iOhX8UmUZ3Od4kDaYtfz3__yac
"""

#########################################
############## FUNCIONES ################
#########################################

# 1. MOSTRAR TABLA

def mostrar_tabla(equipos, partidos):

  ordenar_tabla(equipos, partidos)

  print("TABLA DE POSICIONES")
  print("Equipo | PJ | PG | PE | PP | GF | GC | DG | PTS")

  for equipo in equipos:
    dg = equipo[5] - equipo[6]
    print(equipo[0].upper(), equipo[1], equipo[2], equipo[3], equipo[4], equipo[5], equipo[6], dg, equipo[7])

# 2. PARTIDOS PENDIENTES

def mostrar_partidos_pendientes(partidos):

  print("Partidos pendientes: ")

  for partido in partidos:
    if partido[5] == False:
      print(partido[0], partido[1], 'vs', partido[2])

# 3. PARTIDOS JUGADOS

def mostrar_partidos_jugados(partidos):

  hay_jugados = False

  print("Partidos jugados: ")

  for partido in partidos:
    if partido[5] == True:
      hay_jugados = True
      print(partido[1], partido[3], "-", partido[4], partido[2])
  if hay_jugados == False:
    print("No hay partidos jugados.")

# 4. CARGAR RESULTADOS

def cargar_resultado(partidos):

  mostrar_partidos_pendientes(partidos)
  partido_elegido = None

  while partido_elegido == None:

    try:
      id_elegido = int(input("Seleccione ID del partido: "))

      for partido in partidos:
        if partido[0] == id_elegido:
          if partido[5] == True:
            print("Error. Ese partido ya fue cargado")
          else:
            partido_elegido = partido

      if partido_elegido == None:
        print("Error. Ingrese un ID válido de partido pendiente.")
    except ValueError:
      print("Error. Debe ingresar un número.")

  print("Partido seleccionado: ")
  print(partido_elegido[1], "vs", partido_elegido[2])

  goles_validos = False

  while goles_validos == False:

    try:
      goles1 = int(input("Ingrese goles de " + partido_elegido[1] + ": "))
      goles2 = int(input("Ingrese goles de " + partido_elegido[2] + ": "))
      if goles1 < 0 or goles2 < 0:
        print("Error. Los goles no pueden ser negativos")
      else:
        goles_validos = True

    except ValueError:
      print("Error. Los goles deben ser números enteros")

  partido_elegido[3] = goles1
  partido_elegido[4] = goles2
  partido_elegido[5] = True
  return partido_elegido

# 5. ACTUALIZAR TABLA

def actualizar_tabla(equipos, partido_elegido):

  for equipo in equipos:
    if equipo[0] == partido_elegido[1]:
      equipo[1] +=1 #PJ
      equipo[5] += partido_elegido[3] #GF
      equipo[6] += partido_elegido[4] #GC
    elif equipo[0] == partido_elegido[2]:
      equipo[1] +=1 #PJ
      equipo[5] += partido_elegido[4] #GF
      equipo[6] += partido_elegido[3] #GC

  for equipo in equipos:
    if equipo[0] == partido_elegido[1]:
      if partido_elegido[3] > partido_elegido[4]:
        equipo[2] +=1 #PG
        equipo[7] +=3 #PTS
      elif partido_elegido[3] < partido_elegido[4]:
        equipo[4] +=1 #PP
      else:
        equipo[3] +=1  #PE
        equipo[7] +=1 #PTS
    elif equipo[0] == partido_elegido[2]:
      if partido_elegido[4] > partido_elegido[3]:
        equipo[2] +=1 #PG
        equipo[7] +=3 #PTS
      elif partido_elegido[4] < partido_elegido[3]:
        equipo[4] +=1 #PP
      else:
        equipo[3] +=1  #PE
        equipo[7] +=1 #PTS

# 6. DUELO DIRECTO

def calcular_duelo_directo(nombre1, nombre2, partidos):

  puntos1 = 0
  puntos2 = 0
  dg1 = 0
  dg2 = 0

  for partido in partidos:
    if partido[5] == True:
      if partido[1] == nombre1 and partido[2] == nombre2:
        goles1 = partido[3]
        goles2 = partido[4]

        dg1 = goles1 - goles2
        dg2 = goles2 - goles1

        if goles1 > goles2:
          puntos1 = 3
        elif goles2 > goles1:
          puntos2 = 3
        else:
          puntos1 = 1
          puntos2 = 1
  return puntos1, puntos2, dg1, dg2

# 7. ORDENAR TABLA

def ordenar_tabla(equipos, partidos):

  for i in range(len(equipos)):
    for j in range(i + 1, len(equipos)):
      dg_i = equipos[i][5] - equipos[i][6]
      dg_j = equipos[j][5] - equipos[j][6]

      cambiar = False

      if equipos[j][7] > equipos[i][7]:
        cambiar = True

      elif equipos[j][7] == equipos[i][7]:
        puntos_i, puntos_j, dg_directa_i, dg_directa_j = calcular_duelo_directo(equipos[i][0], equipos[j][0], partidos)
        if puntos_j > puntos_i:
          cambiar = True

        elif puntos_j == puntos_i:
          if dg_directa_j > dg_directa_i:
            cambiar = True

          elif dg_directa_j == dg_directa_i:
            if dg_j > dg_i:
              cambiar = True

      if cambiar == True:
        aux = equipos[i]
        equipos[i] = equipos[j]
        equipos[j] = aux

# 8. ANALIZAR CLASIFICADOS

def analizar_clasificados(equipos, partidos):

  ordenar_tabla(equipos, partidos)
  partidos_jugados = 0

  for partido in partidos:
    if partido[5] == True:
      partidos_jugados += 1
  if partidos_jugados < 6:
    print("Clasifican parcialmente: ")
    print("1°: ", equipos[0][0])
    print("2°: ", equipos[1][0])
    print("Zona de riesgo: ")
    print("3°: ", equipos[2][0])
    print("4°: ", equipos[3][0])
  elif partidos_jugados == 6:
    print("Clasificados: ")
    print("1°: ", equipos[0][0])
    print("2°: ", equipos[1][0])

# 9. MODO SIMULACIÓN

def modo_simulacion(equipos, partidos):
  equipos_simulados = []
  partidos_simulados = []

  for equipo in equipos:
    equipos_simulados.append([equipo[0], equipo[1], equipo[2], equipo[3], equipo[4], equipo[5], equipo[6], equipo[7]])

  for partido in partidos:
    partidos_simulados.append([partido[0], partido[1], partido[2], partido[3], partido[4], partido[5]])

  opcion_simulacion = ""

  while opcion_simulacion != "3":
    print("Modo simulación")
    print("1. Cargar resultado simulado")
    print("2. Ver tabla simulada")
    print("3. Salir de la simulación")

    opcion_simulacion = input("Ingrese opción a simular: ")

    if opcion_simulacion == "1":
      partido_elegido = cargar_resultado(partidos_simulados)
      actualizar_tabla(equipos_simulados, partido_elegido)

    elif opcion_simulacion == "2":
      mostrar_tabla(equipos_simulados, partidos_simulados)

    elif opcion_simulacion == "3":
      print("Saliendo del modo simulación. Los datos reales no fueron modificados.")

    else:
      print("Opción inválida")

# 10. MOSTRAR REPORTE

def mostrar_reporte(equipos, partidos):

  mostrar_partidos_jugados(partidos)
  mostrar_partidos_pendientes(partidos)
  mostrar_tabla(equipos, partidos)
  analizar_clasificados(equipos, partidos)

############################################################
######################## PROGRAMA ##########################
############################################################

# 1. INICIALIZACIÓN

equipos = []

for i in range(4):
  nombre = input("Ingrese nombre del equipo: ")
  equipos.append([nombre, 0, 0, 0, 0, 0, 0, 0])

partidos = []
id = 0

for indice_equipo in range(4):
  for indice_rival in range(indice_equipo + 1, 4):
    id += 1
    equipo1 = equipos[indice_equipo][0]
    equipo2 = equipos[indice_rival][0]
    partidos.append([id, equipo1, equipo2, 0, 0, False])

# 2.MENÚ PRINCIPAL

opcion = ""

while opcion != '4':
  print("MENÚ PRINCIPAL")
  print("1. Ver reporte")
  print("2. Cargar resultado")
  print("3. Modo simulación")
  print("4. Salir")

  opcion = input("Ingrese opción: ")

  if opcion == "1":
    mostrar_reporte(equipos, partidos)

  elif opcion == "2":
    partido_elegido = cargar_resultado(partidos)
    if partido_elegido != None:
      actualizar_tabla(equipos, partido_elegido)

  elif opcion == "3":
    print("Modo simulación: ")
    modo_simulacion(equipos, partidos)

  elif opcion == "4":
    print("Fin del programa: ")

  else:
    print("Opción inválida: ")

  ################################################################
  ########################FIN DEL PROGRAMA########################
  ################################################################

